let id = 1;

const projectList = [
  {
    id: id++,
    title: "This Website",
    link: "something",
    timeline: "Dec 2024 - Present",
    langLib: "React, JSX, CSS",
    scope: "SPA with multiple pages, navigated using React Router",
    collab: "Solo Project",
    image: "src/assets/websiteProject.jpg",
    side: "right",
    summary: "This is summary",
  },
  {
    id: id++,
    title: "This Website",
    link: "something",
    timeline: "Dec 2024 - Present",
    langLib: "something",
    scope: "SPA with multiple pages, navigated using React Router",
    collab: "Solo Project",
    image: "src/assets/websiteProject.jpg",
    side: "left",
    summary: "This is summary",
  },
  {
    id: id++,
    title: "This Website",
    link: "something",
    timeline: "Dec 2024 - Present",
    langLib: "something",
    scope: "SPA with multiple pages, navigated using React Router",
    collab: "Solo Project",
    image: "src/assets/websiteProject.jpg",
    side: "right",
    summary: "This is summary",
  },
  {
    id: id++,
    title: "This Website",
    link: "something",
    timeline: "Dec 2024 - Present",
    langLib: "something",
    scope: "SPA with multiple pages, navigated using React Router",
    collab: "Solo Project",
    image: "src/assets/websiteProject.jpg",
    side: "left",
    summary: "This is summary",
  },
  {
    id: id++,
    title: "This Website",
    link: "something",
    timeline: "Dec 2024 - Present",
    langLib: "something",
    scope: "SPA with multiple pages, navigated using React Router",
    collab: "Solo Project",
    image: "src/assets/websiteProject.jpg",
    side: "right",
    summary: "This is summary",
  }
]

export default projectList